/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  org.lwjgl.opengl.GL11
 */
package com.hbm.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class ModelUzi
extends ModelBase {
    ModelRenderer BodyBack;
    ModelRenderer BodyBottom;
    ModelRenderer BodySide;
    ModelRenderer Ejector;
    ModelRenderer BodyFront;
    ModelRenderer GripFront;
    ModelRenderer StockFront;
    ModelRenderer StockPlate;
    ModelRenderer HandleBase;
    ModelRenderer Handle;
    ModelRenderer HandleBack;
    ModelRenderer HandleBottom;
    ModelRenderer HandlePlate;
    ModelRenderer HandleTop;
    ModelRenderer Muzzle1;
    ModelRenderer Muzzle2;
    ModelRenderer StockBack;
    ModelRenderer StockPlate1;
    ModelRenderer Stock1;
    ModelRenderer Stock2;
    ModelRenderer Stcok3;
    ModelRenderer Stock4;
    ModelRenderer Hump1;
    ModelRenderer Hump2;
    ModelRenderer Hump3;
    ModelRenderer Hump4;
    ModelRenderer Hump5;
    ModelRenderer Hump6;
    ModelRenderer SightBack;
    ModelRenderer Sight1;
    ModelRenderer Sight2;
    ModelRenderer Hump7;
    ModelRenderer Hump8;
    ModelRenderer Hump9;
    ModelRenderer Hump10;
    ModelRenderer Hump11;
    ModelRenderer Hump12;
    ModelRenderer Sight3;
    ModelRenderer SightFront;
    ModelRenderer Knob1;
    ModelRenderer Knob2;
    ModelRenderer Bolt1;
    ModelRenderer Bolt2;
    ModelRenderer Mag;
    ModelRenderer Trigger;
    ModelRenderer Frame1;
    ModelRenderer Frame2;

    public ModelUzi() {
        this.textureWidth = 128;
        this.textureHeight = 64;
        this.BodyBack = new ModelRenderer((ModelBase)this, 0, 0);
        this.BodyBack.addBox(0.0f, 0.0f, 0.0f, 14, 6, 4);
        this.BodyBack.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BodyBack.setTextureSize(128, 64);
        this.BodyBack.mirror = true;
        this.setRotation(this.BodyBack, 0.0f, 0.0f, 0.0f);
        this.BodyBottom = new ModelRenderer((ModelBase)this, 82, 0);
        this.BodyBottom.addBox(0.0f, 0.0f, 0.0f, 6, 3, 4);
        this.BodyBottom.setRotationPoint(-6.0f, 3.0f, 0.0f);
        this.BodyBottom.setTextureSize(128, 64);
        this.BodyBottom.mirror = true;
        this.setRotation(this.BodyBottom, 0.0f, 0.0f, 0.0f);
        this.BodySide = new ModelRenderer((ModelBase)this, 102, 0);
        this.BodySide.addBox(0.0f, 0.0f, 0.0f, 6, 3, 2);
        this.BodySide.setRotationPoint(-6.0f, 0.0f, 0.0f);
        this.BodySide.setTextureSize(128, 64);
        this.BodySide.mirror = true;
        this.setRotation(this.BodySide, 0.0f, 0.0f, 0.0f);
        this.Ejector = new ModelRenderer((ModelBase)this, 102, 5);
        this.Ejector.addBox(0.0f, 0.0f, 0.0f, 6, 3, 2);
        this.Ejector.setRotationPoint(-6.0f, 0.5f, 1.5f);
        this.Ejector.setTextureSize(128, 64);
        this.Ejector.mirror = true;
        this.setRotation(this.Ejector, 0.0f, 0.0f, 0.0f);
        this.BodyFront = new ModelRenderer((ModelBase)this, 36, 0);
        this.BodyFront.addBox(0.0f, 0.0f, 0.0f, 19, 6, 4);
        this.BodyFront.setRotationPoint(-25.0f, 0.0f, 0.0f);
        this.BodyFront.setTextureSize(128, 64);
        this.BodyFront.mirror = true;
        this.setRotation(this.BodyFront, 0.0f, 0.0f, 0.0f);
        this.GripFront = new ModelRenderer((ModelBase)this, 0, 10);
        this.GripFront.addBox(0.0f, 0.0f, 0.0f, 14, 5, 5);
        this.GripFront.setRotationPoint(-24.5f, 1.5f, -0.5f);
        this.GripFront.setTextureSize(128, 64);
        this.GripFront.mirror = true;
        this.setRotation(this.GripFront, 0.0f, 0.0f, 0.0f);
        this.StockFront = new ModelRenderer((ModelBase)this, 38, 10);
        this.StockFront.addBox(0.0f, 0.0f, 0.0f, 14, 3, 4);
        this.StockFront.setRotationPoint(3.0f, 6.0f, 0.0f);
        this.StockFront.setTextureSize(128, 64);
        this.StockFront.mirror = true;
        this.setRotation(this.StockFront, 0.0f, 0.0f, 0.0f);
        this.StockPlate = new ModelRenderer((ModelBase)this, 118, 0);
        this.StockPlate.addBox(0.0f, -4.0f, 0.0f, 1, 4, 4);
        this.StockPlate.setRotationPoint(3.0f, 9.0f, 0.0f);
        this.StockPlate.setTextureSize(128, 64);
        this.StockPlate.mirror = true;
        this.setRotation(this.StockPlate, 0.0f, 0.0f, -0.3490659f);
        this.HandleBase = new ModelRenderer((ModelBase)this, 0, 20);
        this.HandleBase.addBox(0.0f, 0.0f, 0.0f, 12, 3, 5);
        this.HandleBase.setRotationPoint(-10.0f, 4.0f, -0.5f);
        this.HandleBase.setTextureSize(128, 64);
        this.HandleBase.mirror = true;
        this.setRotation(this.HandleBase, 0.0f, 0.0f, 0.0f);
        this.Handle = new ModelRenderer((ModelBase)this, 0, 28);
        this.Handle.addBox(0.0f, 0.0f, 0.0f, 4, 10, 3);
        this.Handle.setRotationPoint(-5.0f, 7.0f, 0.5f);
        this.Handle.setTextureSize(128, 64);
        this.Handle.mirror = true;
        this.setRotation(this.Handle, 0.0f, 0.0f, 0.0f);
        this.HandleBack = new ModelRenderer((ModelBase)this, 14, 28);
        this.HandleBack.addBox(0.0f, 0.0f, 0.0f, 2, 4, 3);
        this.HandleBack.setRotationPoint(-1.0f, 11.0f, 0.5f);
        this.HandleBack.setTextureSize(128, 64);
        this.HandleBack.mirror = true;
        this.setRotation(this.HandleBack, 0.0f, 0.0f, 0.0f);
        this.HandleBottom = new ModelRenderer((ModelBase)this, 14, 35);
        this.HandleBottom.addBox(-2.0f, 0.0f, 0.0f, 2, 3, 3);
        this.HandleBottom.setRotationPoint(1.0f, 15.0f, 0.5f);
        this.HandleBottom.setTextureSize(128, 64);
        this.HandleBottom.mirror = true;
        this.setRotation(this.HandleBottom, 0.0f, 0.0f, 0.7853982f);
        this.HandlePlate = new ModelRenderer((ModelBase)this, 24, 28);
        this.HandlePlate.addBox(-2.0f, -3.0f, 0.0f, 2, 3, 3);
        this.HandlePlate.setRotationPoint(1.0f, 11.0f, 0.5f);
        this.HandlePlate.setTextureSize(128, 64);
        this.HandlePlate.mirror = true;
        this.setRotation(this.HandlePlate, 0.0f, 0.0f, -0.4886922f);
        this.HandleTop = new ModelRenderer((ModelBase)this, 24, 34);
        this.HandleTop.addBox(-2.0f, 0.0f, 0.0f, 2, 3, 3);
        this.HandleTop.setRotationPoint(1.0f, 7.0f, 0.5f);
        this.HandleTop.setTextureSize(128, 64);
        this.HandleTop.mirror = true;
        this.setRotation(this.HandleTop, 0.0f, 0.0f, 0.5235988f);
        this.Muzzle1 = new ModelRenderer((ModelBase)this, 82, 12);
        this.Muzzle1.addBox(0.0f, 0.0f, 0.0f, 3, 3, 2);
        this.Muzzle1.setRotationPoint(-28.0f, 1.5f, 1.0f);
        this.Muzzle1.setTextureSize(128, 64);
        this.Muzzle1.mirror = true;
        this.setRotation(this.Muzzle1, 0.0f, 0.0f, 0.0f);
        this.Muzzle2 = new ModelRenderer((ModelBase)this, 82, 7);
        this.Muzzle2.addBox(0.0f, 0.0f, 0.0f, 3, 2, 3);
        this.Muzzle2.setRotationPoint(-28.0f, 2.0f, 0.5f);
        this.Muzzle2.setTextureSize(128, 64);
        this.Muzzle2.mirror = true;
        this.setRotation(this.Muzzle2, 0.0f, 0.0f, 0.0f);
        this.StockBack = new ModelRenderer((ModelBase)this, 34, 20);
        this.StockBack.addBox(0.0f, 0.0f, 0.0f, 1, 11, 3);
        this.StockBack.setRotationPoint(14.0f, 7.0f, 0.5f);
        this.StockBack.setTextureSize(128, 64);
        this.StockBack.mirror = true;
        this.setRotation(this.StockBack, 0.0f, 0.0f, 0.0f);
        this.StockPlate1 = new ModelRenderer((ModelBase)this, 42, 17);
        this.StockPlate1.addBox(-1.0f, -11.0f, 0.0f, 1, 11, 3);
        this.StockPlate1.setRotationPoint(15.0f, 18.0f, 0.5f);
        this.StockPlate1.setTextureSize(128, 64);
        this.StockPlate1.mirror = true;
        this.setRotation(this.StockPlate1, 0.0f, 0.0f, 0.0959931f);
        this.Stock1 = new ModelRenderer((ModelBase)this, 50, 17);
        this.Stock1.addBox(-1.0f, -3.0f, 0.0f, 1, 3, 4);
        this.Stock1.setRotationPoint(17.0f, 6.0f, 0.0f);
        this.Stock1.setTextureSize(128, 64);
        this.Stock1.mirror = true;
        this.setRotation(this.Stock1, 0.0f, 0.0f, -0.3490659f);
        this.Stock2 = new ModelRenderer((ModelBase)this, 60, 17);
        this.Stock2.addBox(0.0f, -3.0f, 0.0f, 1, 3, 4);
        this.Stock2.setRotationPoint(14.0f, 6.0f, 0.0f);
        this.Stock2.setTextureSize(128, 64);
        this.Stock2.mirror = true;
        this.setRotation(this.Stock2, 0.0f, 0.0f, 0.3490659f);
        this.Stcok3 = new ModelRenderer((ModelBase)this, 50, 24);
        this.Stcok3.addBox(0.0f, 0.0f, 0.0f, 1, 3, 4);
        this.Stcok3.setRotationPoint(15.0f, 3.0f, 0.0f);
        this.Stcok3.setTextureSize(128, 64);
        this.Stcok3.mirror = true;
        this.setRotation(this.Stcok3, 0.0f, 0.0f, 0.0f);
        this.Stock4 = new ModelRenderer((ModelBase)this, 60, 24);
        this.Stock4.addBox(0.0f, 0.0f, 0.0f, 2, 5, 3);
        this.Stock4.setRotationPoint(13.5f, 1.5f, 0.5f);
        this.Stock4.setTextureSize(128, 64);
        this.Stock4.mirror = true;
        this.setRotation(this.Stock4, 0.0f, 0.0f, 0.0f);
        this.Hump1 = new ModelRenderer((ModelBase)this, 74, 10);
        this.Hump1.addBox(-2.0f, -3.0f, 0.0f, 2, 3, 1);
        this.Hump1.setRotationPoint(14.0f, 0.0f, 0.0f);
        this.Hump1.setTextureSize(128, 64);
        this.Hump1.mirror = true;
        this.setRotation(this.Hump1, 0.0f, 0.0f, -0.2617994f);
        this.Hump2 = new ModelRenderer((ModelBase)this, 74, 14);
        this.Hump2.addBox(0.0f, -3.0f, 0.0f, 2, 3, 1);
        this.Hump2.setRotationPoint(10.0f, 0.0f, 0.0f);
        this.Hump2.setTextureSize(128, 64);
        this.Hump2.mirror = true;
        this.setRotation(this.Hump2, 0.0f, 0.0f, 0.2617994f);
        this.Hump3 = new ModelRenderer((ModelBase)this, 74, 18);
        this.Hump3.addBox(0.0f, 0.0f, 0.0f, 2, 1, 1);
        this.Hump3.setRotationPoint(11.0f, -3.0f, 0.0f);
        this.Hump3.setTextureSize(128, 64);
        this.Hump3.mirror = true;
        this.setRotation(this.Hump3, 0.0f, 0.0f, 0.0f);
        this.Hump4 = new ModelRenderer((ModelBase)this, 70, 20);
        this.Hump4.addBox(-2.0f, -3.0f, 0.0f, 2, 3, 1);
        this.Hump4.setRotationPoint(14.0f, 0.0f, 3.0f);
        this.Hump4.setTextureSize(128, 64);
        this.Hump4.mirror = true;
        this.setRotation(this.Hump4, 0.0f, 0.0f, -0.2617994f);
        this.Hump5 = new ModelRenderer((ModelBase)this, 70, 24);
        this.Hump5.addBox(0.0f, -3.0f, 0.0f, 2, 3, 1);
        this.Hump5.setRotationPoint(10.0f, 0.0f, 3.0f);
        this.Hump5.setTextureSize(128, 64);
        this.Hump5.mirror = true;
        this.setRotation(this.Hump5, 0.0f, 0.0f, 0.2617994f);
        this.Hump6 = new ModelRenderer((ModelBase)this, 70, 28);
        this.Hump6.addBox(0.0f, 0.0f, 0.0f, 2, 1, 1);
        this.Hump6.setRotationPoint(11.0f, -3.0f, 3.0f);
        this.Hump6.setTextureSize(128, 64);
        this.Hump6.mirror = true;
        this.setRotation(this.Hump6, 0.0f, 0.0f, 0.0f);
        this.SightBack = new ModelRenderer((ModelBase)this, 80, 17);
        this.SightBack.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1);
        this.SightBack.setRotationPoint(11.5f, -2.0f, 1.5f);
        this.SightBack.setTextureSize(128, 64);
        this.SightBack.mirror = true;
        this.setRotation(this.SightBack, 0.0f, 0.0f, 0.0f);
        this.Sight1 = new ModelRenderer((ModelBase)this, 80, 19);
        this.Sight1.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1);
        this.Sight1.setRotationPoint(11.5f, -1.0f, 1.5f);
        this.Sight1.setTextureSize(128, 64);
        this.Sight1.mirror = true;
        this.setRotation(this.Sight1, 0.0f, 0.0f, 0.0f);
        this.Sight2 = new ModelRenderer((ModelBase)this, 84, 17);
        this.Sight2.addBox(0.0f, 0.0f, 0.0f, 2, 1, 2);
        this.Sight2.setRotationPoint(11.0f, -0.5f, 1.0f);
        this.Sight2.setTextureSize(128, 64);
        this.Sight2.mirror = true;
        this.setRotation(this.Sight2, 0.0f, 0.0f, 0.0f);
        this.Hump7 = new ModelRenderer((ModelBase)this, 94, 7);
        this.Hump7.addBox(-2.0f, -3.0f, 0.0f, 2, 3, 1);
        this.Hump7.setRotationPoint(-21.0f, 0.0f, 0.0f);
        this.Hump7.setTextureSize(128, 64);
        this.Hump7.mirror = true;
        this.setRotation(this.Hump7, 0.0f, 0.0f, -0.2617994f);
        this.Hump8 = new ModelRenderer((ModelBase)this, 94, 11);
        this.Hump8.addBox(0.0f, -3.0f, 0.0f, 2, 3, 1);
        this.Hump8.setRotationPoint(-25.0f, 0.0f, 0.0f);
        this.Hump8.setTextureSize(128, 64);
        this.Hump8.mirror = true;
        this.setRotation(this.Hump8, 0.0f, 0.0f, 0.2617994f);
        this.Hump9 = new ModelRenderer((ModelBase)this, 94, 15);
        this.Hump9.addBox(0.0f, 0.0f, 0.0f, 2, 1, 1);
        this.Hump9.setRotationPoint(-24.0f, -3.0f, 0.0f);
        this.Hump9.setTextureSize(128, 64);
        this.Hump9.mirror = true;
        this.setRotation(this.Hump9, 0.0f, 0.0f, 0.0f);
        this.Hump10 = new ModelRenderer((ModelBase)this, 100, 10);
        this.Hump10.addBox(-2.0f, -3.0f, 0.0f, 2, 3, 1);
        this.Hump10.setRotationPoint(-21.0f, 0.0f, 3.0f);
        this.Hump10.setTextureSize(128, 64);
        this.Hump10.mirror = true;
        this.setRotation(this.Hump10, 0.0f, 0.0f, -0.2617994f);
        this.Hump11 = new ModelRenderer((ModelBase)this, 100, 14);
        this.Hump11.addBox(0.0f, -3.0f, 0.0f, 2, 3, 1);
        this.Hump11.setRotationPoint(-25.0f, 0.0f, 3.0f);
        this.Hump11.setTextureSize(128, 64);
        this.Hump11.mirror = true;
        this.setRotation(this.Hump11, 0.0f, 0.0f, 0.2617994f);
        this.Hump12 = new ModelRenderer((ModelBase)this, 100, 18);
        this.Hump12.addBox(0.0f, 0.0f, 0.0f, 2, 1, 1);
        this.Hump12.setRotationPoint(-24.0f, -3.0f, 3.0f);
        this.Hump12.setTextureSize(128, 64);
        this.Hump12.mirror = true;
        this.setRotation(this.Hump12, 0.0f, 0.0f, 0.0f);
        this.Sight3 = new ModelRenderer((ModelBase)this, 34, 34);
        this.Sight3.addBox(0.0f, 0.0f, 0.0f, 2, 1, 2);
        this.Sight3.setRotationPoint(-24.0f, -0.5f, 1.0f);
        this.Sight3.setTextureSize(128, 64);
        this.Sight3.mirror = true;
        this.setRotation(this.Sight3, 0.0f, 0.0f, 0.0f);
        this.SightFront = new ModelRenderer((ModelBase)this, 34, 37);
        this.SightFront.addBox(0.0f, 0.0f, 0.0f, 1, 2, 0);
        this.SightFront.setRotationPoint(-23.5f, -1.5f, 2.0f);
        this.SightFront.setTextureSize(128, 64);
        this.SightFront.mirror = true;
        this.setRotation(this.SightFront, 0.0f, 0.0f, 0.0f);
        this.Knob1 = new ModelRenderer((ModelBase)this, 42, 31);
        this.Knob1.addBox(0.0f, 0.0f, 0.0f, 2, 2, 2);
        this.Knob1.setRotationPoint(-15.0f, -2.0f, 1.0f);
        this.Knob1.setTextureSize(128, 64);
        this.Knob1.mirror = true;
        this.setRotation(this.Knob1, 0.0f, 0.0f, 0.0f);
        this.Knob2 = new ModelRenderer((ModelBase)this, 50, 31);
        this.Knob2.addBox(-1.0f, 0.0f, -1.0f, 2, 2, 2);
        this.Knob2.setRotationPoint(-14.0f, -2.0f, 2.0f);
        this.Knob2.setTextureSize(128, 64);
        this.Knob2.mirror = true;
        this.setRotation(this.Knob2, 0.0f, 0.7853982f, 0.0f);
        this.Bolt1 = new ModelRenderer((ModelBase)this, 42, 35);
        this.Bolt1.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1);
        this.Bolt1.setRotationPoint(11.5f, -2.0f, -0.5f);
        this.Bolt1.setTextureSize(128, 64);
        this.Bolt1.mirror = true;
        this.setRotation(this.Bolt1, 0.0f, 0.0f, 0.0f);
        this.Bolt2 = new ModelRenderer((ModelBase)this, 46, 35);
        this.Bolt2.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1);
        this.Bolt2.setRotationPoint(11.5f, -2.0f, 3.5f);
        this.Bolt2.setTextureSize(128, 64);
        this.Bolt2.mirror = true;
        this.setRotation(this.Bolt2, 0.0f, 0.0f, 0.0f);
        this.Mag = new ModelRenderer((ModelBase)this, 118, 8);
        this.Mag.addBox(0.0f, 0.0f, 0.0f, 3, 10, 2);
        this.Mag.setRotationPoint(-4.5f, 17.0f, 1.0f);
        this.Mag.setTextureSize(128, 64);
        this.Mag.mirror = true;
        this.setRotation(this.Mag, 0.0f, 0.0f, 0.0f);
        this.Trigger = new ModelRenderer((ModelBase)this, 0, 41);
        this.Trigger.addBox(-1.0f, 0.0f, 0.0f, 1, 3, 1);
        this.Trigger.setRotationPoint(-6.0f, 7.0f, 1.5f);
        this.Trigger.setTextureSize(128, 64);
        this.Trigger.mirror = true;
        this.setRotation(this.Trigger, 0.0f, 0.0f, 0.3490659f);
        this.Frame1 = new ModelRenderer((ModelBase)this, 4, 41);
        this.Frame1.addBox(0.0f, 0.0f, 0.0f, 3, 4, 2);
        this.Frame1.setRotationPoint(-10.0f, 7.0f, 1.0f);
        this.Frame1.setTextureSize(128, 64);
        this.Frame1.mirror = true;
        this.setRotation(this.Frame1, 0.0f, 0.0f, 0.0f);
        this.Frame2 = new ModelRenderer((ModelBase)this, 14, 41);
        this.Frame2.addBox(0.0f, -1.0f, 0.0f, 3, 1, 2);
        this.Frame2.setRotationPoint(-7.0f, 11.0f, 1.0f);
        this.Frame2.setTextureSize(128, 64);
        this.Frame2.mirror = true;
        this.setRotation(this.Frame2, 0.0f, 0.0f, -0.4363323f);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        GL11.glDisable((int)2884);
        this.BodyBack.render(f5);
        this.BodyBottom.render(f5);
        this.BodySide.render(f5);
        this.Ejector.render(f5);
        this.BodyFront.render(f5);
        this.GripFront.render(f5);
        this.StockFront.render(f5);
        this.StockPlate.render(f5);
        this.HandleBase.render(f5);
        this.Handle.render(f5);
        this.HandleBack.render(f5);
        this.HandleBottom.render(f5);
        this.HandlePlate.render(f5);
        this.HandleTop.render(f5);
        this.Muzzle1.render(f5);
        this.Muzzle2.render(f5);
        this.StockBack.render(f5);
        this.StockPlate1.render(f5);
        this.Stock1.render(f5);
        this.Stock2.render(f5);
        this.Stcok3.render(f5);
        this.Stock4.render(f5);
        this.Hump1.render(f5);
        this.Hump2.render(f5);
        this.Hump3.render(f5);
        this.Hump4.render(f5);
        this.Hump5.render(f5);
        this.Hump6.render(f5);
        GL11.glDisable((int)2884);
        this.SightBack.render(f5);
        GL11.glEnable((int)2884);
        this.Sight1.render(f5);
        this.Sight2.render(f5);
        this.Hump7.render(f5);
        this.Hump8.render(f5);
        this.Hump9.render(f5);
        this.Hump10.render(f5);
        this.Hump11.render(f5);
        this.Hump12.render(f5);
        this.Sight3.render(f5);
        this.SightFront.render(f5);
        this.Knob1.render(f5);
        this.Knob2.render(f5);
        this.Bolt1.render(f5);
        this.Bolt2.render(f5);
        this.Mag.render(f5);
        GL11.glDisable((int)2884);
        this.Trigger.render(f5);
        this.Frame1.render(f5);
        this.Frame2.render(f5);
        GL11.glEnable((int)2884);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
}
